export const nfoGames = [
  {
    slug: "lego-batman-legacy-of-the-dark-knight",
    title: "LEGO.Batman.Legacy.of.the.Dark.Knight-voices38",
    format: "ISO",
    releaseDate: "22/05/2026",
    crackDate: "22/05/2026",
    releaseType: "GAME",
    genre: "Batmobile Drifts In Lego City",
    protection: "Denuvo + Steam",
    developer: "TT Games",
    description:
      "LEGO Batman: Legacy of the Dark Knight is a narrative led action-adventure from TT Games, creators of LEGO Star Wars: The Skywalker Saga. Step into Bruce Wayne's journey to become Batman, forging bonds with trusted allies while facing Gotham City's most dangerous and iconic DC Super-Villains. Embark on a journey that begins with the origins of Batman as a young Bruce Wayne trains with The League of Shadows, becomes the hero of Gotham City, and forge a new family of allies with Jim Gordon, Catwoman, Robin, Nightwing, and Batgirl. Confront an ever-growing threat from across Batman's Rogues Gallery as you face The Joker, The Penguin, Mr. Freeze, Poison Ivy, Bane, and more.",
    isoHash:
      "aac62500037ac4b4e2dc0b6ad83700a423eb419eee5b60164a9f86d52501a3d6",
    releaseSupporters: [
      "Badwith_names",
      "DarkMahesvara",
      "ValeQQ",
      "Kuba271K",
      "6 unknown",
    ],
    testers: [
      "wwww",
      "Equine",
      "Nox",
      "Ace<D>Of",
      "Sun_Goku",
      "Arix",
      "K&S",
      "Baklava",
      "Marlboro",
      "ADELOOoO",
      "HP1",
      "BEERLOVER",
      "DRADISContact",
      "ACG",
      "Zuppa",
      "Eru Iluvatar",
      "gregoh",
      "Loozy",
      "DRM-Free-FTW",
      "Marshall Matters",
      "ProfessorMagnum",
      "Nacho",
      "Taiyo",
    ],
    featured: true,
    sortOrder: 0,
  },
  {
    slug: "mafia-the-old-country",
    title: "Mafia.The.Old.Country-voices38",
    format: "ISO",
    releaseDate: "22/05/2026",
    crackDate: "07/08/2025",
    releaseType: "GAME",
    genre: "Horses and Guns",
    protection: "Denuvo + Steam + Custom",
    developer: "Hangar 13",
    description:
      "Experience a gritty mob story set in the brutal underworld of 1900s Sicily. Play as Enzo Favara, a man who endured a brutal childhood of forced labor, as he risks everything to become a man of honor in the Torrisi crime family. Uncover the origins of organized crime in this immersive third-person action-adventure.",
    isoHash:
      "6132bba7313419453d0c874b9a3a0bd07e3458f8e1e9115a405c84f2c342d341",
    releaseSupporters: [
      "Badwith_names",
      "DarkMahesvara",
      "ValeQQ",
      "Kuba271K",
      "6 unknown",
    ],
    testers: [
      "vvvvv",
      "DRADISContact",
      "Nox",
      "Minotaur",
      "Ace<D>0f",
      "ACG",
      "Arix",
      "Solid Snake",
      "Verax",
      "Zuppa",
      "Eru Iluvatar",
      "ZER0x3144",
      "Big Boss",
      "Baklava",
      "gregoh",
      "Loozy",
      "K&S",
      "huckl3b3rry",
      "Sun_Goku",
      "ADELOoo0",
      "Cartman's Crack",
      "HP1",
      "Equine",
      "Beerlover",
      "Dingleberg",
      "mr. Damto",
      "Naos",
      "fckupsymphony",
      "DRM-Free-FTW",
      "Marshall Matters",
      "matec",
      "vimh9",
      "Marlboro",
      "Nacho",
      "Taiyo",
    ],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: "pragmata",
    title: "PRAGMATA-voices38",
    format: "ISO",
    releaseDate: "14/05/2026",
    crackDate: "17/04/2026",
    releaseType: "GAME",
    genre: "Fighting Rogue AI on the Moon",
    protection: "Denuvo + Steam + VMProtect + Custom",
    developer: "Capcom",
    description:
      "Pragmata is a unique, sci-fi action-adventure game from Capcom. Follow Hugh, a member of an ill-fated investigation team, and Diana, a young android, as they navigate a lunar facility taken over by rogue AI in search of a way to Earth. At a remote lunar research facility, humanity discovers a new ore that, when properly refined, can be used to create almost anything using 3D printers. When the facility suddenly falls silent, Hugh and his team are dispatched to investigate... but then disaster strikes. Hugh is saved by Diana, a lone android wandering the complex. The two of them must join forces to find a way off the moon while working their way through an AI-controlled facility bent on stopping them.",
    installNote:
      "If the game can't save, start the exe with admin privileges",
    isoHash:
      "c6ce4c543740e7b64e2f87d2dacd1eab992ee662e622bb0a505ca21a316f6e9f",
    releaseSupporters: [
      "Badwith_names",
      "TigresAPG10",
      "snowyboi",
      "acidmilq",
      "kuba271k",
      "DarkMahesvara",
      "nah",
      "SpecialFor_is_a_Pedo",
      "2 unknown",
    ],
    testers: [
      "DRADISContact",
      "Arix",
      "Ace<D>0",
      "Beerlover",
      "Equine",
      "Nox",
      "Loozy",
      "Dedender",
      "wuuw",
      "Zuppa",
      "Luiji U'Gigant",
      "Baklava",
      "gregoh",
      "Big Boss",
      "Minotaur",
      "HP1",
      "Marlboro",
      "K&S",
      "Sun_Goku",
      "Orange Goober",
      "Eru Iluvatar",
      "IconOfSin",
      "Solid Snake",
      "huckl3h3rry",
      "ZER0x3144",
      "Dingleberg",
      "ACG",
      "DRM-Free-FTW",
      "ADELOoo0",
      "Naos",
      "Verax",
      "Marshall Matters",
      "matec",
      "Nacho",
    ],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: "black-myth-wukong",
    title: "Black.Myth.Wukong-voices38",
    format: "ISO",
    releaseDate: "27/04/2026",
    crackDate: "20/08/2024",
    releaseType: "GAME",
    genre: "Dying Simulator",
    protection: "Denuvo + Steam",
    developer: "Game Science",
    description:
      "Black Myth: Wukong is an action RPG rooted in Chinese mythology. The story is based on Journey to the West, one of the Four Great Classical Novels of Chinese literature. You shall set out as the Destined One to venture into the challenges and marvels ahead, to uncover the obscured truth beneath the veil of a glorious legend from the past.",
    isoHash:
      "5c6f49a7c5fdc5d9f225821a442c29f64f3083d6a819dade63465fa4f0837628",
    releaseSupporters: [
      "Dinka Jester",
      "DarkMahesvara",
      "acidmilq",
      "nsk0",
      "Olivier Monbaron",
      "E",
      "H4X0RUFO",
      "allxtrade",
      "badwith_names",
      "Sqwifty",
      "kuba271k",
      "15 unknown",
    ],
    featured: true,
    sortOrder: 3,
  },
] as const;

export const nfoCryptoWallets = [
  {
    symbol: "BTC",
    address: "bc1q48cvs8awyn07zqz4kvcnum2evdghjs9ruw985x",
  },
  {
    symbol: "XMR",
    address:
      "42tbMLouwxWTq8YMKQMFNF3M2zRTRaabyKhUx5Nhkoov67WxTox9f3E3a3zQWYxJsuJi8hu5V15MWGuTUhY7GNHe3c8A169",
  },
  {
    symbol: "ETH",
    address: "0x31D8A4Cb666C127e08C69F8135Ef8803dDaed61f",
  },
  {
    symbol: "LTC",
    address: "ltc1q9lgajdn6zqr3qyqcpdxulkzxm3suqn0lfd97ja",
  },
  {
    symbol: "DOGE",
    address: "D5QnCycB5e524q2BQWgZaQrGEdhqCu6rwZ",
  },
  {
    symbol: "BHC",
    address: "qpw5hc084gu6eaqnqyyc2thpcpgw6xm6hvfy3dvk29",
  },
  {
    symbol: "SOL",
    address: "ERxDeF4up9mfYnsY5p6QFMoUc8SavGSnxjbAsDYPJRPm",
  },
] as const;

export const nfoSupporters = [
  "Dinka Jester",
  "DarkMahesvara",
  "acidmilq",
  "nsk0",
  "Olivier Monbaron",
  "E",
  "H4X0RUFO",
  "allxtrade",
  "Badwith_names",
  "Sqwifty",
  "kuba271k",
  "TigresAPG10",
  "snowyboi",
  "nah",
  "SpecialFor_is_a_Pedo",
  "ValeQQ",
  "Kuba271K",
] as const;

export const nfoSiteSettings = {
  installationSteps: [
    "Burn or mount the iso",
    "Run setup.exe and install",
    "Copy the crack from voices38 to install dir",
    "Play",
  ],
  notes:
    "Want to support the development of future cracks? You can now donate. All the funds will be used to buy various expensive hardware for testing. The denuvo iterations are getting harder to do properly, so I need hardware, to ensure stability.",
  contactEmail: "voices38@proton.me",
} as const;
