export const portfolioSeedData = {
  releases: [
    {
      id: "007-first-light",
      title: "007.First.Light-voices38",
      format: "ISO",
      releaseDate: "09/06/2026",
      genre: "STEALTH ACTION",
      protection: "DENUVO + CUSTOM",
      downloadUrl: "#",
    },
    {
      id: "cyber-phantom-2077",
      title: "CYBER_PHANTOM_2077",
      format: "BIN",
      releaseDate: "12/04/2026",
      genre: "RPG",
      protection: "STEAM_DRM",
      downloadUrl: "#",
    },
    {
      id: "void-signal-relay",
      title: "VOID_SIGNAL_RELAY",
      format: "ISO",
      releaseDate: "03/15/2026",
      genre: "HORROR",
      protection: "NONE",
      downloadUrl: "#",
    },
    {
      id: "phantom-grid-engine",
      title: "PHANTOM_GRID_ENGINE",
      format: "BIN",
      releaseDate: "01/22/2026",
      genre: "RACING",
      protection: "CUSTOM",
      downloadUrl: "#",
    },
  ],
  archiveReleases: [
    {
      id: "007-first-light",
      title: "007.First.Light-voices38",
      format: "ISO",
      releaseDate: "09/06/2026",
      genre: "STEALTH ACTION",
      protection: "DENUVO + CUSTOM",
      downloadUrl: "#",
    },
    {
      id: "cyber-phantom-2077",
      title: "CYBER_PHANTOM_2077",
      format: "BIN",
      releaseDate: "12/04/2026",
      genre: "RPG",
      protection: "STEAM_DRM",
      downloadUrl: "#",
    },
    {
      id: "void-signal-relay",
      title: "VOID_SIGNAL_RELAY",
      format: "ISO",
      releaseDate: "03/15/2026",
      genre: "HORROR",
      protection: "NONE",
      downloadUrl: "#",
    },
    {
      id: "phantom-grid-engine",
      title: "PHANTOM_GRID_ENGINE",
      format: "BIN",
      releaseDate: "01/22/2026",
      genre: "RACING",
      protection: "CUSTOM",
      downloadUrl: "#",
    },
    {
      id: "neon-drift-zero",
      title: "NEON_DRIFT_ZERO",
      format: "ISO",
      releaseDate: "11/08/2025",
      genre: "ARCADE RACER",
      protection: "NONE",
      downloadUrl: "#",
    },
    {
      id: "static-horizon",
      title: "STATIC_HORIZON",
      format: "BIN",
      releaseDate: "08/19/2025",
      genre: "SURVIVAL",
      protection: "STEAM_DRM",
      downloadUrl: "#",
    },
    {
      id: "cipher-protocol",
      title: "CIPHER_PROTOCOL",
      format: "ISO",
      releaseDate: "05/02/2025",
      genre: "PUZZLE",
      protection: "CUSTOM",
      downloadUrl: "#",
    },
    {
      id: "black-ice-arena",
      title: "BLACK_ICE_ARENA",
      format: "BIN",
      releaseDate: "02/14/2025",
      genre: "FIGHTER",
      protection: "NONE",
      downloadUrl: "#",
    },
    {
      id: "ghost-line-tactics",
      title: "GHOST_LINE_TACTICS",
      format: "ISO",
      releaseDate: "10/30/2024",
      genre: "STRATEGY",
      protection: "DENUVO + CUSTOM",
      downloadUrl: "#",
    },
    {
      id: "pulse-runner-x",
      title: "PULSE_RUNNER_X",
      format: "BIN",
      releaseDate: "07/11/2024",
      genre: "PLATFORMER",
      protection: "NONE",
      downloadUrl: "#",
    },
    {
      id: "deep-signal-v2",
      title: "DEEP_SIGNAL_V2",
      format: "ISO",
      releaseDate: "04/03/2024",
      genre: "ADVENTURE",
      protection: "STEAM_DRM",
      downloadUrl: "#",
    },
    {
      id: "zero-day-legacy",
      title: "ZERO_DAY_LEGACY",
      format: "BIN",
      releaseDate: "01/17/2024",
      genre: "SHOOTER",
      protection: "CUSTOM",
      downloadUrl: "#",
    },
  ],
  projects: [
    {
      id: "nebula-decoder",
      name: "PROJECT_NEBULA_DECODER",
      version: "v0.98-BETA",
      progress: 85,
      eta: "2026-10-15T14:00:00Z",
    },
  ],
  supporters: [
    { name: "Crystal" },
    { name: "Badwith_Names" },
    { name: "nah" },
    { name: "Mod Weath" },
    { name: "kuba271k (x2)" },
    { name: "acidmilq" },
    { name: "DarkMahesvara" },
    { name: "Nitsuga" },
    { name: "Pantheon" },
    { name: "13 unknown" },
  ],
  cryptoWallets: [
    {
      symbol: "BTC",
      address: "bc1q48cvs8awyn07zqz4kvcnum2evdghjs9ruw985x",
    },
    {
      symbol: "XMR",
      address:
        "42tbMLouwxWTq8YMKQMFNF3M2zRTRaabyKhUx5Nhkoov67WxTox9f3E3a3zQWYxJsuJi8hu5V15MWGuTUhY7GNHe3c8A169",
    },
    {
      symbol: "ETH",
      address: "0x31D8A4Cb666C127e08C69F8135Ef8803dDaed61f",
    },
    {
      symbol: "SOL",
      address: "ERxDeF4up9mfYnsY5p6QFMoUc8SavGSnxjbAsDYPJRPm",
    },
  ],
  installationSteps: [
    "Burn or mount the iso",
    "Run setup.exe and install",
    "Copy the crack from voices38 to install dir",
    "Play",
  ],
  notes:
    "Want to support the development of future cracks? You can now donate. All the funds will be used to buy various expensive hardware for testing. The denuvo iterations are getting harder to do properly, so I need hardware, to ensure stability.",
} as const;
